version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: cricgeo_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
