# Generated by Django 5.2.7 on 2025-10-07 07:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=120)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('surface_type', models.CharField(choices=[('grass', 'Grass'), ('dry', 'Dry'), ('dusty', 'Dusty'), ('green', 'Green Top'), ('artificial', 'Artificial')], default='grass', max_length=32)),
                ('current_condition', models.CharField(blank=True, choices=[('batting_friendly', 'Batting friendly'), ('bowling_friendly', 'Bowling friendly'), ('balanced', 'Balanced')], max_length=32, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='geo.stadium')),
            ],
        ),
    ]
